name: Build and Push Docker Image (Multi-Stage-Core-HCM)

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set Timezone to Asia/Colombo
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Asia/Colombo
      run: |
        sudo apt-get update
        echo "tzdata tzdata/Areas select Asia" | sudo debconf-set-selections
        echo "tzdata tzdata/Zones/Asia select Colombo" | sudo debconf-set-selections
        sudo apt-get install -y tzdata
        sudo ln -snf /usr/share/zoneinfo/Asia/Colombo /etc/localtime
        echo "Asia/Colombo" | sudo tee /etc/timezone
        sudo dpkg-reconfigure -f noninteractive tzdata
        date  # Verify the timezone setting
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Inv WebAPI Docker Image
      uses: docker/build-push-action@v4
      with:
        context: src
        file: src/Services/Inventory/Inv.WebAPI/Dockerfile
        push: true
        tags: prasanna1974/invwebapi:latest
